---
- name: Constro Deployment
  hosts: webservers
  remote_user: mayur
  #sudo: yes
  become_method: sudo
  become_user: root
  gather_facts: False
  project_has_composer: yes


  tasks:
   - name: GIT PULL
     git:
       repo: git@github.com:woxiprogrammers/mco.git
       dest: chdir= /usr/share/nginx/html/share/mco
       accept_hostkey: yes
       update: yes

   - name: execute php artisan migrate
     cron: >
       job=" php usr/share/nginx/html/share/mco/artisan migrate"
       state=present
       user=vagrant
       name="php artisan migrate"

     #command: "{{ php artisan migrate }} chdir= /usr/share/nginx/html/share/mco"
    # args:
    #   chdir: /usr/share/nginx/html/share/mco

   - name: execute command for seeders
     command: php artisan db:seed
     args:
       chdir: /usr/share/nginx/html/share/mco

   - name: execute npm run production
     npm:
       path: /usr/share/nginx/html/share/mco/node_modules/
       production: yes

   - name: execute clear cache
     command: php artisan cache:clear
     args:
       chdir: /usr/share/nginx/html/share/mco
