---
- name: Constro Deployment
  hosts: webservers
  remote_user: mayur
#  sudo: yes
  become_method: sudo
  become_user: vagrant


  tasks:
   - name: GIT PULL
     git:
       repo: git@github.com:woxiprogrammers/mco.git
       dest: chdir= /usr/share/nginx/html/share/mco
       accept_hostkey: yes
       update: yes

   - name: execute php artisan migrate
     command: 'php artisan migrate'
     args:
       chdir:  chdir= /usr/share/nginx/html/share/mco/

   - name: execute command for seeders
     command: chdir= /usr/share/nginx/html/share/mco/ php artisan db:seed

   - name: execute npm run production
     shell: chdir= /usr/share/nginx/html/share/mco/ sudo npm run production

   - name: execute clear cache
     command: chdir= /usr/share/nginx/html/share/mco/ php artisan cache:clear
