---
- name: Constro Deployment
  hosts: webservers
  remote_user: mayur
#  sudo: yes
  become_method: sudo
  become_user: vagrant


  tasks:
   - name: GIT PULL
     git:
       repo: git@github.com:woxiprogrammers/mco.git
       dest: chdir= /usr/share/nginx/html/share/mco
       update: yes
       register: app_checkout_result

   - name: Run migration job
     command: php artisan migrate
     when: app_checkout_result.changed




   - name: execute command for seeders
     command: chdir= /usr/share/nginx/html/share/mco/ php artisan db:seed #--class=UpdateBillStatusesTableSeeder

   - name: execute npm run production
     shell: chdir= /usr/share/nginx/html/share/mco/ sudo npm run production

   - name: execute clear cache
     command: chdir= /usr/share/nginx/html/share/mco/ php artisan cache:clear

   #- name: install composer
    # apt: name=composer state=present update_cache=yes
